/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.time.LocalDate;

/**
 *
 * @author User
 */
public class AddCropForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddCropForm.class.getName());
    /**
     * Creates new form AddCropForm
     */
    public AddCropForm() {
        initComponents();
        lblWarning.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblwelcm = new javax.swing.JLabel();
        lblPlantDate = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlReturn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCropName = new javax.swing.JLabel();
        lblWarning = new javax.swing.JLabel();
        txtCrName = new javax.swing.JTextField();
        lblAmount1 = new javax.swing.JLabel();
        lblPlantDate1 = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        comboCategory = new javax.swing.JComboBox<>();
        dateHarvest = new com.github.lgooddatepicker.components.DatePicker();
        datePlant = new com.github.lgooddatepicker.components.DatePicker();
        comboLandunit = new javax.swing.JComboBox<>();
        comboQuantityunit = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblwelcm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblwelcm.setText("Add Your Crops ");
        jPanel2.add(lblwelcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lblPlantDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPlantDate.setText("Planting Date");
        jPanel2.add(lblPlantDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        pnlAdd.setBackground(new java.awt.Color(0, 153, 255));
        pnlAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddMouseExited(evt);
            }
        });
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add");
        pnlAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel2.add(pnlAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 110, 40));

        pnlReturn.setBackground(new java.awt.Color(0, 153, 255));
        pnlReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReturnMouseExited(evt);
            }
        });
        pnlReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Return");
        pnlReturn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel2.add(pnlReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 110, 40));

        lblCropName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCropName.setText("Crop Name");
        jPanel2.add(lblCropName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        lblWarning.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 51));
        lblWarning.setText("Warning");
        jPanel2.add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 440, -1));
        jPanel2.add(txtCrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 280, -1));

        lblAmount1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAmount1.setText("Category");
        jPanel2.add(lblAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        lblPlantDate1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPlantDate1.setText("Harvest Date");
        jPanel2.add(lblPlantDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        lblSize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSize.setText("Land Size");
        jPanel2.add(lblSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        txtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeActionPerformed(evt);
            }
        });
        jPanel2.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 180, -1));

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQuantity.setText("Quantity");
        jPanel2.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel2.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 180, -1));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatus.setText("Status");
        jPanel2.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Growing", "Ready to harvest", "Damaged", "Harvested" }));
        jPanel2.add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 280, -1));

        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Vegetables", "Fruits", "Grains" }));
        jPanel2.add(comboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 280, -1));
        jPanel2.add(dateHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 280, -1));
        jPanel2.add(datePlant, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 280, -1));

        comboLandunit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Acres", "Hectares", "Square Meters (m²)", "Square Feet (ft²)", " " }));
        jPanel2.add(comboLandunit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 90, -1));

        comboQuantityunit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "kg", "g", "Tonnes", "Bags", "Boxes", "Pieces" }));
        jPanel2.add(comboQuantityunit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 790, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlAdd, color1, color2);
       
        if(txtCrName.getText().isEmpty()||datePlant.getText().isEmpty()||dateHarvest.getText().isEmpty()||txtSize.getText().isEmpty()||txtQuantity.getText().isEmpty())
        {
            lblWarning.setText("Fill all fields first!");
            lblWarning.setVisible(true);
        }
        else if(datePlant.getText().isEmpty()||dateHarvest.getText().isEmpty())
        {
            lblWarning.setText("Please enter valid Dates");
            lblWarning.setVisible(true);
        }
        else if(datePlant.getText().equals(dateHarvest.getText()))
        {
            lblWarning.setText("Planting date and Harvest date cannot be the same!");
            lblWarning.setVisible(true);
        }
        else if(comboCategory.getSelectedIndex()==0)
        {
            lblWarning.setText("Please select a Crop category");
            lblWarning.setVisible(true);
        }
        else if(comboStatus.getSelectedIndex()==0)
        {
            lblWarning.setText("Please select Crop status");
            lblWarning.setVisible(true);
        }
        else if(comboLandunit.getSelectedIndex() == 0)
        {
            lblWarning.setText("Please select quantity unit");
            lblWarning.setVisible(true);
        }
        else if(comboQuantityunit.getSelectedIndex()==0)
        {
            lblWarning.setText("Please select Land size unit");
            lblWarning.setVisible(true);
        }
        else
        {
            Connection conn = null;
            UserDetails details = new UserDetails();
            try
            {
                String crop = txtCrName.getText();
                String category = comboCategory.getSelectedItem().toString();
                LocalDate localPlantDate = datePlant.getDate();
                LocalDate localHarvestDate = dateHarvest.getDate();
                String size = txtSize.getText()+""+comboLandunit.getSelectedItem().toString();
                String quantity = txtQuantity.getText()+""+comboQuantityunit.getSelectedItem().toString();
                String status = comboStatus.getSelectedItem().toString();
                
                Date plantDate = Date.valueOf(localPlantDate);
                Date harvestDate = Date.valueOf(localHarvestDate);
                
                
                conn = DBconnection.getConnection();
                
                String query = "INSERT INTO crops (farmerId,crop_name,category,planting_date,harvest_date,land_size,quantity,status)VALUES(?,?,?,?,?,?,?,?)";
                
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setInt(1,DBvalidation.checkId(details.getUsername()));
                
                ps.setString(2,crop);
                ps.setString(3,category);
                ps.setDate(4,plantDate);
                ps.setDate(5,harvestDate);
                ps.setString(6,size);
                ps.setString(7,quantity);
                ps.setString(8,status);
                
                ps.executeUpdate();
                
            }
            catch(Exception e)
            {
                if(conn != null)
                {
                    JOptionPane.showMessageDialog(null,"Error while trying to add Crop data into database: "+e);
                }
            }
        }
        
            
    }//GEN-LAST:event_pnlAddMouseClicked

    private void pnlAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseEntered
        pnlAdd.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlAddMouseEntered

    private void pnlAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseExited
        pnlAdd.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlAddMouseExited

    private void pnlReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlReturn, color1, color2);
        this.dispose();
        
        
        
    }//GEN-LAST:event_pnlReturnMouseClicked

    private void pnlReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseEntered
        pnlReturn.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlReturnMouseEntered

    private void pnlReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseExited
        pnlReturn.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlReturnMouseExited

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddCropForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboLandunit;
    private javax.swing.JComboBox<String> comboQuantityunit;
    private javax.swing.JComboBox<String> comboStatus;
    private com.github.lgooddatepicker.components.DatePicker dateHarvest;
    private com.github.lgooddatepicker.components.DatePicker datePlant;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JLabel lblCropName;
    private javax.swing.JLabel lblPlantDate;
    private javax.swing.JLabel lblPlantDate1;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JLabel lblwelcm;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JTextField txtCrName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
