/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdminForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminForm.class.getName());

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblwelcm.setText("Welcome, "+UserDetails.getUsername());
        lblFarmers.setText(AdminDashboard.loadFarmerCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblwelcm = new javax.swing.JLabel();
        pnlViewCropReport = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblBuyers = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblFarmers = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblFO = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblHCrops = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblRTHCrops = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblTCrops = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblDCrops = new javax.swing.JLabel();
        pnlAddAdmin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlLogout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblwelcm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblwelcm.setText("Welcome! (name)");
        jPanel3.add(lblwelcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pnlViewCropReport.setBackground(new java.awt.Color(0, 153, 255));
        pnlViewCropReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlViewCropReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlViewCropReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlViewCropReportMouseExited(evt);
            }
        });
        pnlViewCropReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("View Crop Inventory Report");
        pnlViewCropReport.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.add(pnlViewCropReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 220, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Buyer Count");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        lblBuyers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBuyers.setForeground(new java.awt.Color(51, 51, 51));
        lblBuyers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuyers.setText("buyers");
        jPanel2.add(lblBuyers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 210, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFarmers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFarmers.setForeground(new java.awt.Color(51, 51, 51));
        lblFarmers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFarmers.setText("farmers");
        jPanel4.add(lblFarmers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Farmer Count");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 70));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Field Officer Count");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        lblFO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFO.setForeground(new java.awt.Color(51, 51, 51));
        lblFO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFO.setText("field officers");
        jPanel5.add(lblFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 210, 70));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crop Details");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Harvested");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        lblHCrops.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHCrops.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHCrops.setText("hCrops");
        jPanel8.add(lblHCrops, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, -1));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 150, 60));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ready to Harvest");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        lblRTHCrops.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRTHCrops.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRTHCrops.setText("rthCrops");
        jPanel10.add(lblRTHCrops, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, -1));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 60));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total Crops");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        lblTCrops.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTCrops.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTCrops.setText("tCrops");
        jPanel11.add(lblTCrops, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 60));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Damaged");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        lblDCrops.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDCrops.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDCrops.setText("dCrops");
        jPanel12.add(lblDCrops, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, -1));

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 150, 60));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 730, 130));

        pnlAddAdmin.setBackground(new java.awt.Color(0, 153, 255));
        pnlAddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddAdminMouseExited(evt);
            }
        });
        pnlAddAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Admin");
        pnlAddAdmin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPanel3.add(pnlAddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 220, 40));

        pnlLogout.setBackground(new java.awt.Color(0, 153, 255));
        pnlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseExited(evt);
            }
        });
        pnlLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Log out");
        pnlLogout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel3.add(pnlLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 770, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadDashboard()
    {
        
    }
    
    
    private void pnlViewCropReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCropReportMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlViewCropReport, color1, color2);
        Connection conn = null;
        try
        {
            conn = DBconnection.getConnection();
            String reportPath = "src/FarmerReport.jrxml";
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error trying to Display report: "+e);
        }
        finally
        {
            if(conn != null)
            {
                try
                {
                    conn = DBconnection.getConnection();
                    
                    String reportPath = "C:\\NIBM\\EAD\\CourseWork\\Smart-Agriculture-Management-System\\src\\coursework\\Reports\\FarmerReport.jrxml";
                    
                    JasperReport jasperReport = JasperCompileManager.compileReport(reportPath);
                    
                    HashMap<String, Object> parameters = new HashMap<>();
                    
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
                    
                    JasperViewer.viewReport(jasperPrint, false);
                    
                }
                catch(Exception e)
                {
                    System.out.println("Error trying to close connection:"+e);
                }
            }
        }
    }//GEN-LAST:event_pnlViewCropReportMouseClicked

    private void pnlViewCropReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCropReportMouseEntered
        pnlViewCropReport.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlViewCropReportMouseEntered

    private void pnlViewCropReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCropReportMouseExited
        pnlViewCropReport.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlViewCropReportMouseExited

    private void pnlAddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddAdminMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlAddAdmin, color1, color2);
    }//GEN-LAST:event_pnlAddAdminMouseClicked

    private void pnlAddAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddAdminMouseEntered
        pnlAddAdmin.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlAddAdminMouseEntered

    private void pnlAddAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddAdminMouseExited
        pnlAddAdmin.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlAddAdminMouseExited

    private void pnlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlLogout, color1, color2);
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out", "Log out", JOptionPane.YES_NO_OPTION);

        if(choice == JOptionPane.YES_OPTION )
        {
            this.dispose();
            LoginForm f = new LoginForm();
            f.setVisible(true);
        }
    }//GEN-LAST:event_pnlLogoutMouseClicked

    private void pnlLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseEntered
        pnlLogout.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlLogoutMouseEntered

    private void pnlLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseExited
        pnlLogout.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblBuyers;
    private javax.swing.JLabel lblDCrops;
    private javax.swing.JLabel lblFO;
    private javax.swing.JLabel lblFarmers;
    private javax.swing.JLabel lblHCrops;
    private javax.swing.JLabel lblRTHCrops;
    private javax.swing.JLabel lblTCrops;
    private javax.swing.JLabel lblwelcm;
    private javax.swing.JPanel pnlAddAdmin;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlViewCropReport;
    // End of variables declaration//GEN-END:variables
}
