/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdminAddForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminAddForm.class.getName());

    /**
     * Creates new form AdminAddForm
     */
    public AdminAddForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblWarning.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWarning = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcpw = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtuname = new javax.swing.JTextField();
        txtpw = new javax.swing.JTextField();
        pnlReturn = new javax.swing.JPanel();
        lblReturn = new javax.swing.JLabel();
        pnlAddAdmin = new javax.swing.JPanel();
        lblSignup = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add a new Admin");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        lblWarning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(204, 0, 0));
        lblWarning.setText("Warning");
        jPanel2.add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 400, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Username");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        jPanel2.add(txtcpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 240, -1));
        jPanel2.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 240, -1));
        jPanel2.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 240, -1));
        jPanel2.add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 240, -1));

        pnlReturn.setBackground(new java.awt.Color(0, 153, 255));
        pnlReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReturnMouseExited(evt);
            }
        });
        pnlReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReturn.setForeground(new java.awt.Color(255, 255, 255));
        lblReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturn.setText("Return");
        pnlReturn.add(lblReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 30));

        jPanel2.add(pnlReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 120, 30));

        pnlAddAdmin.setBackground(new java.awt.Color(0, 153, 255));
        pnlAddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddAdminMouseExited(evt);
            }
        });
        pnlAddAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSignup.setForeground(new java.awt.Color(255, 255, 255));
        lblSignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignup.setText("Signup");
        pnlAddAdmin.add(lblSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 30));

        jPanel2.add(pnlAddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 120, 30));
        jPanel2.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 240, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Last Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 620, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseClicked

        Color color2 = new Color(153,255,255);
        Color color1 = new Color(0,153,255);
        Functions.mouseClick(pnlReturn,color1,color2);
        this.dispose();
    }//GEN-LAST:event_pnlReturnMouseClicked

    private void pnlReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseEntered
        pnlReturn.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlReturnMouseEntered

    private void pnlReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseExited
        pnlReturn.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlReturnMouseExited

    private void pnlAddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddAdminMouseClicked
        Color color2 = new Color(153,255,255);
        Color color1 = new Color(0,153,255);
        Functions.mouseClick(pnlAddAdmin,color1,color2);

        if(txtfname.getText().isEmpty()||txtlname.getText().isEmpty()||txtuname.getText().isEmpty()||txtpw.getText().isEmpty()||txtcpw.getText().isEmpty())
        {
            lblWarning.setText("Please fill in all fields");
            lblWarning.setVisible(true);
        }
        else if(txtpw.getText().equals(txtcpw.getText())== false)
        {
            lblWarning.setText("Passwords does not match");
            lblWarning.setVisible(true);
        }
        else if(txtpw.getText().length()<6)
        {
            lblWarning.setText("Password must be atleast 6 characters");
            lblWarning.setVisible(true);
        }
        else
        {
            Connection conn = null;

            try
            {
                String name = txtfname.getText()+" "+txtlname.getText();
                String uname= txtuname.getText();
                String pw = txtpw.getText();
                try
                {
                    String dbname = DBvalidation.checkUser(uname);
                    if(dbname != null)
                    {
                        lblWarning.setText("Username already exsits");
                        lblWarning.setVisible(true);
                    }
                    else
                    {
                        conn = DBconnection.getConnection();

                        String query ="INSERT into users(name,username,password,role) VALUES(?,?,?,?)";
                        PreparedStatement ps = conn.prepareStatement(query);
                        ps.setString(1,name);
                        ps.setString(2,uname);
                        ps.setString(3,pw);
                        ps.setString(4,"Admin");

                        ps.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Admin Account created successfully");
                        this.dispose();
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Error while trying to search username: "+e);
                    System.out.println(e);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error while trying to create Account"+e);
                System.out.println(e);
            }
            finally
            {
                if(conn != null)
                {
                    try
                    {
                        conn.close();
                    }
                    catch(Exception e)
                    {
                        System.out.println("Error while trying to close Connection: "+e);
                    }

                }
            }
        }
    }//GEN-LAST:event_pnlAddAdminMouseClicked

    private void pnlAddAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddAdminMouseEntered
        pnlAddAdmin.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlAddAdminMouseEntered

    private void pnlAddAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddAdminMouseExited
        pnlAddAdmin.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlAddAdminMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminAddForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblSignup;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPanel pnlAddAdmin;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JTextField txtcpw;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtpw;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
