/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class BuyerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuyerForm.class.getName());
    /**
     * Creates new form buyerForm
     */
    public BuyerForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblwelcm.setText("Welcome, "+UserDetails.getUsername());
        
        LocalDate today = LocalDate.now();
        lbldate.setText("Today is: "+today.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblwelcm = new javax.swing.JLabel();
        pnlLogout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlViewCr = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlSend = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlViewRq = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblwelcm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblwelcm.setText("Welcome! (name)");
        jPanel2.add(lblwelcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, -1, -1));

        pnlLogout.setBackground(new java.awt.Color(0, 153, 255));
        pnlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseClicked(evt);
            }
        });
        pnlLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Log out");
        pnlLogout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel2.add(pnlLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 110, 40));

        pnlViewCr.setBackground(new java.awt.Color(0, 153, 255));
        pnlViewCr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlViewCrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlViewCrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlViewCrMouseExited(evt);
            }
        });
        pnlViewCr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("View Available Crops");
        pnlViewCr.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jPanel2.add(pnlViewCr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 360, 50));

        pnlSend.setBackground(new java.awt.Color(0, 153, 255));
        pnlSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSendMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSendMouseExited(evt);
            }
        });
        pnlSend.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Send Request");
        pnlSend.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPanel2.add(pnlSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 360, 50));

        pnlViewRq.setBackground(new java.awt.Color(0, 153, 255));
        pnlViewRq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlViewRqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlViewRqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlViewRqMouseExited(evt);
            }
        });
        pnlViewRq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("View My Requests");
        pnlViewRq.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jPanel2.add(pnlViewRq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 360, 50));

        lbldate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldate.setText("date");
        jPanel2.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, 830, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);
        
        Functions.mouseClick(pnlLogout, color1, color2);
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out", "Log out", JOptionPane.YES_NO_OPTION);
        
                if(choice == JOptionPane.YES_OPTION )
                {
                    this.dispose();
                    LoginForm f = new LoginForm();
                    f.setVisible(true);
                }
    }//GEN-LAST:event_pnlLogoutMouseClicked

    private void pnlViewCrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCrMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        
        Functions.mouseClick(pnlViewCr, color1, color2);
    }//GEN-LAST:event_pnlViewCrMouseClicked

    private void pnlSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSendMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        
        Functions.mouseClick(pnlSend, color1, color2);
    }//GEN-LAST:event_pnlSendMouseClicked

    private void pnlViewRqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewRqMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        
        Functions.mouseClick(pnlViewRq, color1, color2);
    }//GEN-LAST:event_pnlViewRqMouseClicked

    private void pnlViewCrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCrMouseEntered
        pnlViewCr.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlViewCrMouseEntered

    private void pnlSendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSendMouseEntered
        pnlSend.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlSendMouseEntered

    private void pnlViewRqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewRqMouseEntered
        pnlViewRq.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlViewRqMouseEntered

    private void pnlViewCrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCrMouseExited
        pnlViewCr.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlViewCrMouseExited

    private void pnlSendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSendMouseExited
        pnlSend.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlSendMouseExited

    private void pnlViewRqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewRqMouseExited
        pnlViewRq.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlViewRqMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuyerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblwelcm;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlSend;
    private javax.swing.JPanel pnlViewCr;
    private javax.swing.JPanel pnlViewRq;
    // End of variables declaration//GEN-END:variables
}
