/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.LocalDate;

/**
 *
 * @author User
 */
public class FarmerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FarmerForm.class.getName());
    
    /**
     * Creates new form officerForm
     */
    public FarmerForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        LocalDate today = LocalDate.now();
        
        
        lblwelcm.setText("Welcome, "+UserDetails.getUsername());
        lblCropCount.setText(DBCrops.loadCropCount(UserDetails.getId()));
        lblRTHCrops.setText(DBCrops.loadHarvestReadyCount(UserDetails.getId()));
        lblNextHarvestDate.setText(DBCrops.loadNextHarvest(UserDetails.getId()));
        lbldate.setText("Today is: "+today.toString());
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblwelcm = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlViewCr = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlViewRec = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlLogout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        pnlLogout1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlEdit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblRTHCrops = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblNextHarvestDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblCropCount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblwelcm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblwelcm.setText("Welcome! (name)");
        jPanel2.add(lblwelcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnlAdd.setBackground(new java.awt.Color(0, 153, 255));
        pnlAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddMouseExited(evt);
            }
        });
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Crops");
        pnlAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jPanel2.add(pnlAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 360, 50));

        pnlViewCr.setBackground(new java.awt.Color(0, 153, 255));
        pnlViewCr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlViewCrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlViewCrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlViewCrMouseExited(evt);
            }
        });
        pnlViewCr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("View Crops");
        pnlViewCr.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jPanel2.add(pnlViewCr, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 360, 50));

        pnlViewRec.setBackground(new java.awt.Color(0, 153, 255));
        pnlViewRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlViewRecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlViewRecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlViewRecMouseExited(evt);
            }
        });
        pnlViewRec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("View Recommendations");
        pnlViewRec.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jPanel2.add(pnlViewRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 360, 50));

        pnlLogout.setBackground(new java.awt.Color(0, 153, 255));
        pnlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseExited(evt);
            }
        });
        pnlLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Log out");
        pnlLogout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel2.add(pnlLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 110, 40));

        lbldate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldate.setText("Today Is, (date)");
        jPanel2.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        pnlLogout1.setBackground(new java.awt.Color(0, 153, 255));
        pnlLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLogout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLogout1MouseExited(evt);
            }
        });
        pnlLogout1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Log out");
        pnlLogout1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel2.add(pnlLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 110, 40));

        pnlEdit.setBackground(new java.awt.Color(0, 153, 255));
        pnlEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlEditMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Profile");
        pnlEdit.add(jLabel9);

        jPanel2.add(pnlEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 90, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRTHCrops.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRTHCrops.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRTHCrops.setText("crops");
        jPanel4.add(lblRTHCrops, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 40, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ready To Harvest");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 160, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Overview");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNextHarvestDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNextHarvestDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNextHarvestDate.setText("crops");
        jPanel5.add(lblNextHarvestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Next Harvest");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, 90));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCropCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCropCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCropCount.setText("crops");
        jPanel6.add(lblCropCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 40, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Your Crop Count");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 90));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 580, 170));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 850, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);
        
        Functions.mouseClick(pnlLogout, color1, color2);
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out", "Log out", JOptionPane.YES_NO_OPTION);
        
                if(choice == JOptionPane.YES_OPTION )
                {
                    this.dispose();
                    LoginForm f = new LoginForm();
                    f.setVisible(true);
                }
    }//GEN-LAST:event_pnlLogoutMouseClicked

    private void pnlAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);
        
        Functions.mouseClick(pnlAdd, color1, color2);
        
        FarmerAddCropForm f = new FarmerAddCropForm ();
        f.setVisible(true);
        
        
    }//GEN-LAST:event_pnlAddMouseClicked

    private void pnlViewCrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCrMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);
        
        Functions.mouseClick(pnlViewCr, color1, color2);
        
        FarmerViewCropsForm f = new FarmerViewCropsForm();
        f.setVisible(true);
    }//GEN-LAST:event_pnlViewCrMouseClicked

    private void pnlViewRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewRecMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);
        
        Functions.mouseClick(pnlViewRec, color1, color2);  
        FarmerReccForm form = new FarmerReccForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlViewRecMouseClicked

    private void pnlAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseEntered
        pnlAdd.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlAddMouseEntered

    private void pnlViewCrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCrMouseEntered
        pnlViewCr.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlViewCrMouseEntered

    private void pnlViewRecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewRecMouseEntered
        pnlViewRec.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlViewRecMouseEntered

    private void pnlLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseEntered
        pnlLogout.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlLogoutMouseEntered

    private void pnlAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseExited
        pnlAdd.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlAddMouseExited

    private void pnlViewCrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewCrMouseExited
        pnlViewCr.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlViewCrMouseExited

    private void pnlViewRecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewRecMouseExited
        pnlViewRec.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlViewRecMouseExited

    private void pnlLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseExited
        pnlLogout.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlLogoutMouseExited

    private void pnlLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlLogout1MouseClicked

    private void pnlLogout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlLogout1MouseEntered

    private void pnlLogout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlLogout1MouseExited

    private void pnlEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);
        
        Functions.mouseClick(pnlEdit, color1, color2);  
        ProfileForm pf = new ProfileForm();
        pf.setVisible(true);
    }//GEN-LAST:event_pnlEditMouseClicked

    private void pnlEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditMouseEntered
        pnlEdit.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlEditMouseEntered

    private void pnlEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditMouseExited
        pnlEdit.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlEditMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FarmerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCropCount;
    private javax.swing.JLabel lblNextHarvestDate;
    private javax.swing.JLabel lblRTHCrops;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblwelcm;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlLogout1;
    private javax.swing.JPanel pnlViewCr;
    private javax.swing.JPanel pnlViewRec;
    // End of variables declaration//GEN-END:variables
}
