/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FarmerPReqUpdateForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FarmerPReqUpdateForm.class.getName());
    int reqId;
    /**
     * Creates new form FarmerPReqUpdateForm
     */
    public FarmerPReqUpdateForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblWarning.setVisible(false);
    }
    
    public void setData(int reqId)
    {
        this.reqId = reqId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlReturn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlUpdate = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblWarning = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        lblwelcm2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlReturn.setBackground(new java.awt.Color(0, 153, 255));
        pnlReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReturnMouseExited(evt);
            }
        });
        pnlReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Return");
        pnlReturn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel1.add(pnlReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, 40));

        pnlUpdate.setBackground(new java.awt.Color(0, 153, 255));
        pnlUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseExited(evt);
            }
        });
        pnlUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Update");
        pnlUpdate.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel1.add(pnlUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 110, 40));

        lblWarning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 51));
        lblWarning.setText("warning");
        jPanel1.add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 270, -1));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Approved", "Rejected", "Pending" }));
        jPanel1.add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 250, -1));

        lblwelcm2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblwelcm2.setText("Update Requst Status");
        jPanel1.add(lblwelcm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlReturn, color1, color2);
        this.dispose();
        FarmerPReqsForm form = new FarmerPReqsForm();
        form.setVisible(true);
    }//GEN-LAST:event_pnlReturnMouseClicked

    private void pnlReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseEntered
        pnlReturn.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlReturnMouseEntered

    private void pnlReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseExited
        pnlReturn.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlReturnMouseExited

    private void pnlUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlUpdate, color1, color2);

        if(comboStatus.getSelectedIndex()== 0)
        {
            lblWarning.setText("Please select request status");
            lblWarning.setVisible(true);
        }    
        else
        {
            String status = comboStatus.getSelectedItem().toString();
            if(DBdisplaytable.updateReqStatus(reqId, status))
            {
                FarmerPReqsForm f = new FarmerPReqsForm();
                f.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null,"Request status updated successfully");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Request status update failed");
            }
            
        }
    }//GEN-LAST:event_pnlUpdateMouseClicked

    private void pnlUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlUpdateMouseEntered

    private void pnlUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlUpdateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FarmerPReqUpdateForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JLabel lblwelcm2;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JPanel pnlUpdate;
    // End of variables declaration//GEN-END:variables
}
