/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FieldOfficerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FieldOfficerForm.class.getName());
    /**
     * Creates new form farmerForm
     */
    public FieldOfficerForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblwelcm.setText("Welcome, "+UserDetails.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblwelcm = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblLogout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlView = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlUpdate = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblwelcm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblwelcm.setText("Welcome! (name)");
        jPanel2.add(lblwelcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, -1, -1));

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDate.setText("date");
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblLogout.setBackground(new java.awt.Color(0, 153, 255));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
        });
        lblLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Log out");
        lblLogout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel2.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 110, 40));

        pnlView.setBackground(new java.awt.Color(0, 153, 255));
        pnlView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlViewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlViewMouseExited(evt);
            }
        });
        pnlView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("View Farmers");
        pnlView.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPanel2.add(pnlView, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 360, 50));

        pnlUpdate.setBackground(new java.awt.Color(0, 153, 255));
        pnlUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseExited(evt);
            }
        });
        pnlUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Update Crop Health");
        pnlUpdate.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jPanel2.add(pnlUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 360, 50));

        pnlAdd.setBackground(new java.awt.Color(0, 153, 255));
        pnlAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddMouseExited(evt);
            }
        });
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Add Recommendations");
        pnlAdd.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jPanel2.add(pnlAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 360, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, 820, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);
        
        Functions.mouseClick(lblLogout, color1, color2);
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out", "Log out", JOptionPane.YES_NO_OPTION);
        
                if(choice == JOptionPane.YES_OPTION )
                {
                    this.dispose();
                    LoginForm f = new LoginForm();
                    f.setVisible(true);
                }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void pnlViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        
        Functions.mouseClick(pnlView, color1, color2);
    }//GEN-LAST:event_pnlViewMouseClicked

    private void pnlUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        
        Functions.mouseClick(pnlUpdate, color1, color2);
    }//GEN-LAST:event_pnlUpdateMouseClicked

    private void pnlAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        
        Functions.mouseClick(pnlAdd, color1, color2);
    }//GEN-LAST:event_pnlAddMouseClicked

    private void pnlViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewMouseEntered
        pnlView.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlViewMouseEntered

    private void pnlUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseEntered
        pnlUpdate.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlUpdateMouseEntered

    private void pnlAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseEntered
        pnlAdd.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlAddMouseEntered

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void pnlViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewMouseExited
        pnlView.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlViewMouseExited

    private void pnlUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseExited
        pnlUpdate.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlUpdateMouseExited

    private void pnlAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseExited
        pnlAdd.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlAddMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FieldOfficerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JPanel lblLogout;
    private javax.swing.JLabel lblwelcm;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JPanel pnlUpdate;
    private javax.swing.JPanel pnlView;
    // End of variables declaration//GEN-END:variables
}
