/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;

/**
 *
 * @author User
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());
    String Role ="";
    
    public LoginForm() {
        initComponents();
        lblWarning.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnlBuyer = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        lblRole1 = new javax.swing.JLabel();
        pnlCreateAcc = new javax.swing.JPanel();
        lblRole5 = new javax.swing.JLabel();
        pnlFO = new javax.swing.JPanel();
        lblRole3 = new javax.swing.JLabel();
        pnlFarmer = new javax.swing.JPanel();
        lblRole4 = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblRole6 = new javax.swing.JLabel();
        txtpw = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lblWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, -1));
        jPanel2.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 320, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Role");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, -1));

        pnlBuyer.setBackground(new java.awt.Color(0, 204, 255));
        pnlBuyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBuyerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBuyerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBuyerMouseExited(evt);
            }
        });
        pnlBuyer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("Buyer");
        pnlBuyer.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, -1));

        jPanel2.add(pnlBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 100, 40));

        lblRole1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole1.setText("Please select a role from below to continue");
        jPanel2.add(lblRole1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 310, -1));

        pnlCreateAcc.setBackground(new java.awt.Color(0, 153, 255));
        pnlCreateAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCreateAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCreateAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCreateAccMouseExited(evt);
            }
        });
        pnlCreateAcc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRole5.setForeground(new java.awt.Color(255, 255, 255));
        lblRole5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole5.setText("Create Account");
        pnlCreateAcc.add(lblRole5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, -1));

        jPanel2.add(pnlCreateAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 300, 50));

        pnlFO.setBackground(new java.awt.Color(0, 204, 255));
        pnlFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlFOMouseExited(evt);
            }
        });
        pnlFO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole3.setForeground(new java.awt.Color(255, 255, 255));
        lblRole3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole3.setText("Field Officer");
        pnlFO.add(lblRole3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, -1));

        jPanel2.add(pnlFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, 40));

        pnlFarmer.setBackground(new java.awt.Color(0, 204, 255));
        pnlFarmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlFarmerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlFarmerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlFarmerMouseExited(evt);
            }
        });
        pnlFarmer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole4.setForeground(new java.awt.Color(255, 255, 255));
        lblRole4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole4.setText("Farmer");
        pnlFarmer.add(lblRole4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, -1));

        jPanel2.add(pnlFarmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, 40));

        pnlLogin.setBackground(new java.awt.Color(0, 153, 255));
        pnlLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLoginMouseExited(evt);
            }
        });
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRole6.setForeground(new java.awt.Color(255, 255, 255));
        lblRole6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole6.setText("Log in");
        pnlLogin.add(lblRole6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 60, -1));

        jPanel2.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 300, 50));
        jPanel2.add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 320, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, -1));

        lblWarning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning.setText("invalid text here");
        jPanel2.add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 320, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 440, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoginMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        Functions.mouseClick(pnlLogin,color1,color2);
        
        if(txtuname.getText().isEmpty()||txtpw.getText().isEmpty())
        {
            lblWarning.setText("Please fill in all fields to continue");
        }
        
    }//GEN-LAST:event_pnlLoginMouseClicked

    private void pnlCreateAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreateAccMouseClicked
        
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        Functions.mouseClick(pnlCreateAcc,color1,color2);
        
        this.dispose();
        SignupForm f1 = new SignupForm();
        f1.setVisible(true);
    }//GEN-LAST:event_pnlCreateAccMouseClicked

    private void pnlLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoginMouseEntered
        pnlLogin.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlLoginMouseEntered

    private void pnlLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoginMouseExited
        pnlLogin.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlLoginMouseExited

    private void pnlCreateAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreateAccMouseEntered
        pnlCreateAcc.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlCreateAccMouseEntered

    private void pnlCreateAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreateAccMouseExited
        pnlCreateAcc.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlCreateAccMouseExited

    private void pnlFarmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFarmerMouseClicked
        Color color1 = new Color(0,204,255);
        Color color2 = new Color(153,255,255);
        Functions.mouseClick(pnlFarmer,color1,color2);
        Role = "Farmer";
    }//GEN-LAST:event_pnlFarmerMouseClicked

    private void pnlFarmerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFarmerMouseEntered
        pnlFarmer.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_pnlFarmerMouseEntered

    private void pnlFarmerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFarmerMouseExited
        pnlFarmer.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlFarmerMouseExited

    private void pnlFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFOMouseClicked
        Color color1 = new Color(0,204,255);
        Color color2 = new Color(153,255,255);
        Functions.mouseClick(pnlFO,color1,color2);
        Role = "Field Officer";
    }//GEN-LAST:event_pnlFOMouseClicked

    private void pnlFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFOMouseEntered
        pnlFO.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_pnlFOMouseEntered

    private void pnlFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFOMouseExited
        pnlFO.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlFOMouseExited

    private void pnlBuyerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBuyerMouseClicked
        Color color1 = new Color(0,204,255);
        Color color2 = new Color(153,255,255);
        Functions.mouseClick(pnlBuyer,color1,color2);
        Role = "Buyer";
    }//GEN-LAST:event_pnlBuyerMouseClicked

    private void pnlBuyerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBuyerMouseEntered
        pnlBuyer.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_pnlBuyerMouseEntered

    private void pnlBuyerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBuyerMouseExited
        pnlBuyer.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlBuyerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblRole3;
    private javax.swing.JLabel lblRole4;
    private javax.swing.JLabel lblRole5;
    private javax.swing.JLabel lblRole6;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPanel pnlBuyer;
    private javax.swing.JPanel pnlCreateAcc;
    private javax.swing.JPanel pnlFO;
    private javax.swing.JPanel pnlFarmer;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField txtpw;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
