/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author User
 */
public class ProfileForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfileForm.class.getName());

    /**
     * Creates new form ProfileForm
     */
    public ProfileForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblWarning.setVisible(false);
        
        txtUsername.setText(UserDetails.getUsername());
        lblRole.setText(UserDetails.getRole());
        txtName.setText(DBvalidation.checkName(txtUsername.getText().trim()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblProfileForm = new javax.swing.JLabel();
        pnlPfp = new javax.swing.JPanel();
        lblWarning = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlReturn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlUpdate = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPw = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfileForm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblProfileForm.setText("Your Profile,");
        jPanel2.add(lblProfileForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        pnlPfp.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.add(pnlPfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 80));

        lblWarning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 51));
        lblWarning.setText("warning");
        jPanel2.add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 510, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        pnlReturn.setBackground(new java.awt.Color(0, 153, 255));
        pnlReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReturnMouseExited(evt);
            }
        });
        pnlReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Return");
        pnlReturn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel2.add(pnlReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 110, 40));

        pnlUpdate.setBackground(new java.awt.Color(0, 153, 255));
        pnlUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUpdateMouseExited(evt);
            }
        });
        pnlUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Update");
        pnlUpdate.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel2.add(pnlUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 110, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Role:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));
        jPanel2.add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 230, -1));
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 230, -1));

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setText("role");
        jPanel2.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 0, 570, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlReturn, color1, color2);
        this.dispose();
    }//GEN-LAST:event_pnlReturnMouseClicked

    private void pnlReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseEntered
        pnlReturn.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlReturnMouseEntered

    private void pnlReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseExited
        pnlReturn.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlReturnMouseExited

    private void pnlUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlUpdate, color1, color2);
        if(txtUsername.getText().isBlank()||txtPw.getText().isEmpty())
        {
            lblWarning.setText("Please fill fields to update");
            lblWarning.setVisible(true);
        }
        else if(DBvalidation.checkUserPassword(UserDetails.getUsername(),txtPw.getText().trim())==false)
        {
            lblWarning.setText("Wrong account password!");
            lblWarning.setVisible(true);
        }
        else
        {
            String user = txtUsername.getText();
            String name = txtName.getText();
            int id = DBvalidation.checkId(user);
            Connection conn = null ;
            try
            {
                conn = DBconnection.getConnection();
                
                String query = "UPDATE USERS set name=? , username=? WHERE id=?";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1,name);
                ps.setString(2,user);
                ps.setInt(3,id);
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"User Details changed successfully!");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Failed to update profile"+e);
            }
            finally
            {
                if(conn != null)
                {
                    try
                    {
                        conn.close();
                    }
                    catch(Exception e)
                    {
                        System.out.println("error while trying to close connection");
                    }
                }
            }
        }
    }//GEN-LAST:event_pnlUpdateMouseClicked

    private void pnlUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseEntered
        pnlUpdate.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlUpdateMouseEntered

    private void pnlUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpdateMouseExited
        pnlUpdate.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlUpdateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProfileForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblProfileForm;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPanel pnlPfp;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JPanel pnlUpdate;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
