/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.*;
import java.sql.PreparedStatement;
import javax.swing.*;
import javax.swing.Timer;
import java.sql.DriverManager;
import java.sql.Connection;

/**
 *
 * @author User
 */
public class SignupForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignupForm.class.getName());

    /**
     * Creates new form SignupForm
     */
    public SignupForm() {
        initComponents();
        lblWarning.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnlReturn = new javax.swing.JPanel();
        lblRole5 = new javax.swing.JLabel();
        rbBuyer = new javax.swing.JRadioButton();
        rbFarmer = new javax.swing.JRadioButton();
        rbFO = new javax.swing.JRadioButton();
        txtpw = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtcpw = new javax.swing.JPasswordField();
        txtlname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pnlSignup = new javax.swing.JPanel();
        lblRole7 = new javax.swing.JLabel();
        pnlClear = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 100, -1));
        jPanel2.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 320, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Role");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 100, 30));

        pnlReturn.setBackground(new java.awt.Color(0, 153, 255));
        pnlReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReturnMouseExited(evt);
            }
        });
        pnlReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRole5.setForeground(new java.awt.Color(255, 255, 255));
        lblRole5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole5.setText("Return");
        pnlReturn.add(lblRole5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, -1));

        jPanel2.add(pnlReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 300, 50));

        buttonGroup1.add(rbBuyer);
        rbBuyer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbBuyer.setText("Buyer");
        jPanel2.add(rbBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 80, 30));

        buttonGroup1.add(rbFarmer);
        rbFarmer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbFarmer.setText("Farmer");
        jPanel2.add(rbFarmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 80, 30));

        buttonGroup1.add(rbFO);
        rbFO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbFO.setText("Field Officer");
        jPanel2.add(rbFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 110, 30));
        jPanel2.add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 320, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 170, -1));
        jPanel2.add(txtcpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 320, -1));
        jPanel2.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 320, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Last Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("First Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, -1));
        jPanel2.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 320, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Username");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 100, -1));

        pnlSignup.setBackground(new java.awt.Color(0, 153, 255));
        pnlSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSignupMouseExited(evt);
            }
        });
        pnlSignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRole7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRole7.setForeground(new java.awt.Color(255, 255, 255));
        lblRole7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole7.setText("Sign Up");
        lblRole7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRole7MouseClicked(evt);
            }
        });
        pnlSignup.add(lblRole7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, -1));

        jPanel2.add(pnlSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 300, 50));

        pnlClear.setBackground(new java.awt.Color(0, 153, 255));
        pnlClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlClearMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clear");
        pnlClear.add(jLabel2);

        jPanel2.add(pnlClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 100, 30));

        lblWarning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning.setText("invalid text here");
        jPanel2.add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 320, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 440, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseEntered
        pnlReturn.setBackground(new Color(0,204,255));        
    }//GEN-LAST:event_pnlReturnMouseEntered

    private void pnlReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseExited
        pnlReturn.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlReturnMouseExited

    private void pnlReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseClicked

        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        Functions.mouseClick(pnlReturn,color1,color2);
        LoginForm form = new LoginForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlReturnMouseClicked

    private void lblRole7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRole7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRole7MouseClicked

    private void pnlSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignupMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        Functions.mouseClick(pnlSignup,color1,color2);
        
        if(txtfname.getText().isEmpty()||txtlname.getText().isEmpty()||txtuname.getText().isEmpty()||txtpw.getText().isEmpty()||txtcpw.getText().isEmpty())
        {
            lblWarning.setText("Please fill in all fields to continue");
        }
    }//GEN-LAST:event_pnlSignupMouseClicked

    private void pnlSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignupMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlSignupMouseEntered

    private void pnlSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignupMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlSignupMouseExited

    private void pnlClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClearMouseClicked
        Color color1 = new Color(153,255,255);
        Color color2 = new Color(0,153,255);
        Functions.mouseClick(pnlClear,color1,color2);
        
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to clear all fields?", "Confirm clear", JOptionPane.YES_NO_OPTION);
        
        if(choice == JOptionPane.YES_OPTION)
        {
            txtfname.setText("");
            txtlname.setText("");
            txtuname.setText("");
            txtpw.setText("");
            txtcpw.setText("");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_pnlClearMouseClicked

    private void pnlClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClearMouseEntered
        pnlClear.setBackground(new Color(0,204,255)); 
    }//GEN-LAST:event_pnlClearMouseEntered

    private void pnlClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClearMouseExited
        pnlClear.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlClearMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignupForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRole5;
    private javax.swing.JLabel lblRole7;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPanel pnlClear;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JPanel pnlSignup;
    private javax.swing.JRadioButton rbBuyer;
    private javax.swing.JRadioButton rbFO;
    private javax.swing.JRadioButton rbFarmer;
    private javax.swing.JPasswordField txtcpw;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpw;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
