/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Color;

/**
 *
 * @author User
 */
public class ViewCropsFarmerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewCropsFarmerForm.class.getName());

    /**
     * Creates new form ViewCropsFarmerForm
     */
    public ViewCropsFarmerForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblwelcm = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlReturn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCrops = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblwelcm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblwelcm.setText("View Crops");
        jPanel3.add(lblwelcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        pnlAdd.setBackground(new java.awt.Color(0, 153, 255));
        pnlAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddMouseExited(evt);
            }
        });
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add");
        pnlAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel3.add(pnlAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 110, 40));

        pnlReturn.setBackground(new java.awt.Color(0, 153, 255));
        pnlReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReturnMouseExited(evt);
            }
        });
        pnlReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Return");
        pnlReturn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jPanel3.add(pnlReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 110, 40));

        tblCrops.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Crop Name", "Quantity", "Unit Price", "Farmer"
            }
        ));
        jScrollPane1.setViewportView(tblCrops);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 700, 210));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 870, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseExited
        pnlReturn.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlReturnMouseExited

    private void pnlReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseEntered
        pnlReturn.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlReturnMouseEntered

    private void pnlReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlReturn, color1, color2);
        this.dispose();
        AddCropForm f = new AddCropForm();
        f.setVisible(true);
    }//GEN-LAST:event_pnlReturnMouseClicked

    private void pnlAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseExited
        pnlAdd.setBackground(new Color(0,153,255));
    }//GEN-LAST:event_pnlAddMouseExited

    private void pnlAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseEntered
        pnlAdd.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_pnlAddMouseEntered

    private void pnlAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseClicked
        Color color1 = new Color(0,153,255);
        Color color2 = new Color(153,255,255);

        Functions.mouseClick(pnlAdd, color1, color2);

    }//GEN-LAST:event_pnlAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewCropsFarmerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblwelcm;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JTable tblCrops;
    // End of variables declaration//GEN-END:variables
}
